# Config for SSD detector with ResNet50 backbone
model:
  backbone: "resnet50"
  backbone_weights: "IMAGENET_V2"
  neck: "DenseFPN"
  image_size: 300
  n_classes: 80            # without "background"
  sync_batchnorm: False    # syncrhronize BN calculation across all GPUs
  inference:
    min_score: 0.05
    max_overlap: 0.45
    top_k: 200

train:
  num_epochs: 65
  lr_milestones: [42, 53] 
  warmup_epochs: 2    # (1 for basic SSD, 2 for neck case)
  accumulation_steps: 1 
  weight_decay: 0.0005
  initial_lr: 0.0026       # 2.6e-3 
  momentum: 0.9
  warmup_lr: 0.000001       # 1e-6  (1e-5 for basic SSD, 1e-6 for neck case)
  lr_decay_rate: 0.1
  warmup_prefix: True
  max_grad_norm: 5.0        # no gradient clipping
  min_lr: 0               # just for code compatibility, not needed here
  
  batch_size: 64           # (4 gpus) * (64 per each) --> 256 (total)  | maybe should increase to ...
  batch_interval: 100      # we have ~460 batches      
  num_workers: 8           # 8 regardless of number of CPUs/GPUs
  save_every: 15
  snapshot_path: 'model_snapshot.pth'

dataset:
  name: "COCO-2020"
  root: "/opt/software/datasets/COCO" 
  image_size: 300
  n_classes: 80        # without "background"
  test_crop: True      # whether to crop images for test
  test_shuffle: False  # whether to shuffle images for test
