# Standard Swin-T classification config
model:
  backbone: "resnet50"
  backbone_weights: "IMAGENET_V2"
  n_classes: 80
  emb_dim: 96
  depths: [2, 2, 6, 2]
  n_heads: [3, 6, 12, 24]
  mlp_drop: 0.0
  attn_drop: 0.0
  drop_path: 0.2

training:
  num_epochs: 300
  warmup_epochs: 20
  accumulation_steps: 1
  warmup_prefix: True
  initial_lr: 0.0005      # 5e-4
  min_lr: 0.000005        # 5e-6
  warmup_lr: 0.0000005    # 5e-7
  max_grad_norm: 5.0      # as in authors' code
  weight_decay: 0.05
  batch_size: 4         # (4 gpus) * (256 per each) 
  batch_interval: 100     # with bs=1024 -> we have ~1250 batches   
  num_workers: 2          # 8 regardless of number of CPUs/GPUs
  save_every: 20
  snapshot_path: 'model_snapshot.pth'

dataset:
  name: "COCO-2020"
  root: "/opt/software/datasets/COCO" 
  img_size: 224
  num_classes: 1000
  interpolation: 'bicubic'
  test_crop: True      # whether to crop images for test
  test_shuffle: False  # whether to shuffle images for test
  aug:
    color_jitter: 0.4
    auto_augment: 'rand-m9-mstd0.5-inc1'
    reprob: 0.25
    remode: 'pixel'
    recount: 1
    mixup: 0.8
    cutmix: 1.0
    cutmix_minmax: ~    # -> None
    mixup_prob: 1.0
    mixup_switch_prob: 0.5
    mixup_mode: 'batch'
    label_smoothing: 0.1
